name: smart_trip_planner
description: A flutter project for planning trips with smart features.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0
  hive: ^2.2.3
  http: ^1.4.0
  fpdart: ^1.1.1
  path_provider: ^2.1.0
  uuid: ^4.3.3
  intl: ^0.20.2
  get_it: ^8.0.3
  url_launcher: ^6.3.2
  hive_flutter: ^1.1.0
  provider: ^6.1.5
  connectivity_plus: ^6.1.4
  google_sign_in: ^6.1.0
  flutter_riverpod: ^2.6.1
  speech_to_text: 7.1.0
  permission_handler: ^11.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  hive_generator: ^2.0.1
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  #assets:
  #  - assets/images/g-logo-2.png