// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:
        'AIzaSyCi1ginTmZ8mFhoP5GHYbzMbuijEds_tc4', // ConfigService.firebaseWebApiKey, // Note: Use env vars in production
    appId: '1:608392516852:web:a57862c94b42367e87baa1',
    messagingSenderId: '608392516852',
    projectId: 'smart-trip-planner-flutter',
    authDomain: 'smart-trip-planner-flutter.firebaseapp.com',
    storageBucket: 'smart-trip-planner-flutter.firebasestorage.app',
    measurementId: 'G-6V5XQCB7K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'AIzaSyBX8IwcEF00JKednTMYvRKPtmqiVbQ-Qp4', // ConfigService.firebaseAndroidApiKey, // Note: Use env vars in production
    appId: '1:608392516852:android:1fb53d115d5a90d087baa1',
    messagingSenderId: '608392516852',
    projectId: 'smart-trip-planner-flutter',
    storageBucket: 'smart-trip-planner-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:
        'AIzaSyBxVxP5sIVREaHBKpmovqZEpayLmL1hDeI', // ConfigService.firebaseIosApiKey, // Note: Use env vars in production
    appId: '1:608392516852:ios:286217b3414f3e5b87baa1',
    messagingSenderId: '608392516852',
    projectId: 'smart-trip-planner-flutter',
    storageBucket: 'smart-trip-planner-flutter.firebasestorage.app',
    iosBundleId: 'com.example.smartTripPlannerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey:
        'AIzaSyBxVxP5sIVREaHBKpmovqZEpayLmL1hDeI', // ConfigService.firebaseIosApiKey, // Note: Use env vars in production
    appId: '1:608392516852:ios:286217b3414f3e5b87baa1',
    messagingSenderId: '608392516852',
    projectId: 'smart-trip-planner-flutter',
    storageBucket: 'smart-trip-planner-flutter.firebasestorage.app',
    iosBundleId: 'com.example.smartTripPlannerFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey:
        'AIzaSyCi1ginTmZ8mFhoP5GHYbzMbuijEds_tc4', // ConfigService.firebaseWebApiKey, // Note: Use env vars in production
    appId: '1:608392516852:web:ba0c8f5d8736e81c87baa1',
    messagingSenderId: '608392516852',
    projectId: 'smart-trip-planner-flutter',
    authDomain: 'smart-trip-planner-flutter.firebaseapp.com',
    storageBucket: 'smart-trip-planner-flutter.firebasestorage.app',
    measurementId: 'G-N8QB80Y6VW',
  );
}
